title: "ALIGEGE BLOG"
description: "很高兴能在这里与你分享我对技术和生活的思考。"
url: https://linzx91.github.io
baseurl: ""
author: "Aligege"
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-mdui.gemspec
  - LICENSE.txt
  - README.md
  - vendor
  - docs