head: 
   favicon: "http://lc-lbnmv7xc.cn-e1.lcfile.com/23524f44d0dbda8a8b8d/56F06ECF-CB2C-4EB6-B224-FA5239175167.png" #  the favicon
   high_res_favicon: "http://lc-lbnmv7xc.cn-e1.lcfile.com/2dbf72e175302067d7aa/95E88963-A726-420D-96A8-419DBA32B02B.png" #  the favicon using high quality format
   apple_touch_icon: "http://lc-lbnmv7xc.cn-e1.lcfile.com/e94db32f1ae4f5296ef5/05F6DD92-5FA1-4F48-9824-8EC26044BDB7.png" # the iOS Home button icon
   keywords: "个人博客" #  the site keywords

uiux:
   android_chrome_color: "rgba(238, 238, 238, 0.9)" #  the color of the Chrome address bar
   nprogress_color: "#29d" #  the color of the top loading progress bar
   nprogress_buffer: 200 # the top loading progress bar buffers
   meng: true # meng

background: 
   purecolor: "rgba(238, 238, 238, 0.9)" # the background color

img: 
   avatar: "https://images-1259468288.cos.ap-guangzhou.myqcloud.com/img/avatar.jpeg" # your avatar

card: 
   card_shadow: 2 # card shadow (0-24), 0 is not displayed
   card_hoverable: true # When the hover to deepen the shadow

many_authors: false

sns_share: # SNS Share Switch
   twitter: true
   facebook: true
   googleplus: false
   weibo: true
   linkedin: true
   qq: true
   telegram: true
  
comment:
  used: "disqus" # disqus,livere,gitment,valine,vssue
  # disqus config
  disqus_shortname: "aligegeblog" # Your disqus 
  disqus_button: true # disqus load button
  disqus_proxy: false # # disqus proxy(Do not use)
  disqus_proxy_url: "" # (Do not use)
  disqus_api_key: "" # (Do not use)
  # livere config
  livere_type: 'city'
  livere_data_uid: ''
  # gitment config
  owner: ""
  repo: ""
  client_id: ""
  client_secret: ""
  #valine config
  valine_notify: false #mail notifier
  valine_verify: false #validation code
  valine_app_id: 'LbNmV7xclW3Oox6EKv7RRaT7-9Nh9j0Va'
  valine_app_key: 'iHpgXhiVmUvE8A8T2IpbD3ao'
  valine_placeholder: "✎ 写评论…"

prism:
  themes: prism-okaidia
  components: 
    - bash 
  plugins: 

mathjax: true

google_analytics: "UA-142139913-1"  # google analytics code

baidu_site_verification: ""  # baidu site verification code
google_site_verification: "XUXuiWEysvTUtgmy7rMLr3id1e0wP1GW1jR1FauzppU"  # google search console verification code

baidu_auto_push: true  # if you used baidu auto push to commit links

lang: "zh-CN"  # lang

deploy: "" # if you used coding pages

custom_css: "" # Use the assets/css/customCss.css

custom_js: "" # Use the assets/js/customJS.js